name       : haskell-stringsearch
version    : 0.3.6.6
release    : 1
source     :
    - https://hackage.haskell.org/package/stringsearch-0.3.6.6/stringsearch-0.3.6.6.tar.gz : 295f1971920bc52263d8275d7054ad223a7e1aefe75533f9887735c9644ffe4a
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides several functions to quickly search for substrings in strict or lazy ByteStrings.
description: |
    This package provides several functions to quickly search for substrings in strict or lazy ByteStrings. It also provides functions for breaking or splitting on substrings and replacing all occurrences of a substring (the first in case of overlaps) with another. GHC before 6.10 are no longer supported, other compilers only if they support BangPatterns. If you need it to work with other compilers, send a feature request.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    sed -i "s|0.4|0.5|g" stringsearch.cabal
    sed -i "s|< 4|< 5|g" stringsearch.cabal
    sed -i "s|0.6|0.7|g" stringsearch.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
